### ISSUE TITLE
What are the requirements for the Pyhton version of the test environment, torch version, and other installation packages

### ISSUE THREAD

**Issue by Zenobia7** [FanChiMao/HWMNet#1]
when I used  python==3.7.7 torch=1.5.0 run demo.py,The following problems arise：

> AttributeError: module 'torch.nn' has no attribute 'PixelUnshuffle'
I checked all the files and could not find install.md, so I would like to ask what the test environment is. Is this because my Torch version does not match?

**Comment by FanChiMao** [comment]
Hello,

The HWMNet is built in PyTorch 1.8.0 and tested on Windows10 environment (Python: 3.8, CUDA: 10.2, cudnn: 7.6).

Yes! The [nn.PixelUnshuffle](https://pytorch.org/docs/1.8.0/generated/torch.nn.PixelUnshuffle.html#torch.nn.PixelUnshuffle) didn't support until the torch version [v1.8.0](https://pytorch.org/docs/1.8.0/).

You should upgrade the torch version, or try to directly add the source code of [nn.PixelUnshuffle](https://github.com/fangwei123456/PixelUnshuffle-pytorch/blob/master/PixelUnshuffle/__init__.py) in [HWMNet.py](https://github.com/FanChiMao/HWMNet/blob/main/model/HWMNet.py).

As for the other installation packages, I am not sure because I use single pytorch environment with lots of packages... 
(I will form a habit to record the packages for each project in the future)
But at least contain the following packages:
```
matplotlib
scikit-image
opencv-python
yacs
yaml
natsort
h5py
tqdm
```
If there still happen the module error, maybe you  could install them one-by-one...  :(
