### ISSUE TITLE
MIT_5K pretrained weight does not match the results from the paper

### ISSUE THREAD

**Issue by FireWallDragonDarkFluid** [FanChiMao/HWMNet#11]
Hi!
From the pretrained weight provided here: https://drive.google.com/file/d/1ErcewI9mTWzJXOm14iWYNaM8qC6srCoK/view, 
and the MIT_5K dataset provided here: https://drive.google.com/drive/folders/18bTBJX34I3CjAb9qBDxvHWRPQLYSQcld
The metrics, PSNR and SSIM, are far worse than the results recorded in the paper.
I assume there might be some misupload of the dataset or the pretrained weight, 
would you might take a look at the result from your pretrained weight of MIT_5K?

**Comment by FanChiMao** [comment]
Hello, can you provide the screenshot for bad PSNR and SSIM results? 

Because I reran the process and the results were the same.

Do you follow the [**readme**](https://github.com/FanChiMao/HWMNet/blob/main/README.md) instruction using [**evaluate.py**](https://github.com/FanChiMao/HWMNet/blob/main/evaluation.py) to calculate PSNR, SSIM along with the Y-axis?
